server:
  port: 8080
spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        prefix: service
        file-extension: yaml
        group: DEFAULT_GROUP
  application:
    name: nacos-server
